language: cpp
sudo: required
dist: trusty
compiler: gcc

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq g++-6
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
 - sudo apt-get install xorg-dev
 - sudo apt-get install libfreetype6-dev
 - sudo apt-get install liblua5.2-dev
 - git clone https://github.com/glfw/glfw.git
 - cd glfw/ && mkdir build && cd build && cmake .. && sudo make install && cd .. && cd ..

script:
 - mkdir build
 - cd build
 - cmake .. -DEXAMPLES=On
 - make -j2
